yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/api/urls.py
from django.conf.urls import url
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework import routers

from .views import *

router = routers.DefaultRouter()
router.register(r'posts', PostViewSet,
                basename='posts')
router.register(r'posts/(?P<post_id>\d+)/comments', CommentViewSet,
                basename='comments')
router.register(r'groups', GroupViewSet, basename='groups')
router.register(r'follow', FollowViewSet, basename='follow')

router.register(r'users', UserViewSet, basename='users')

urlpatterns = [
    path('v1/jwt/', include('api.inner', namespace='api')),
    path('v1/', include(router.urls)),

]

schema_view = get_schema_view(
    openapi.Info(
        title="Post API",
        default_version='v1',
        description="Документация для приложения api проекта Hw05",
        # terms_of_service="URL страницы с пользовательским соглашением",
        contact=openapi.Contact(email="umbra-mortis@mail.ru"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns += [
    url(r'^swagger(?P<format>\.json|\.yaml)$',
        schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0),
        name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0),
        name='schema-redoc'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("api/", include("api.urls")),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path("", include("posts.urls")),
    path('about/', include('about.urls', namespace='about')),
]

handler403 = 'posts.views.csrf_failure'
handler404 = 'posts.views.page404'
handler500 = 'posts.views.page500'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    # import debug_toolbar

    # urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

yatube/templates/misc/base.html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} |
    Yatube</title>
  <!-- Загрузка статики -->
  {% load static %}
  <link rel="stylesheet"
        href="{% static '/bootstrap/dist/css/bootstrap.min.css' %}">
  <script src="{% static '/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static '/bootstrap/dist/js/bootstrap.min.js' %}"></script>
  <link rel="stylesheet"
        href="{% static '/font-awesome-4.7.0/css/font-awesome.min.css' %}">

  <script src="{% static 'posts/style.css' %}"></script>
  <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
</head>

<body>

{% include 'misc/nav.html' %}
<main>
  <div class="container py-5">
    <h1>{% block header %}{% endblock %}</h1>
    {% block content %}
      <!-- Содержимое страницы -->
    {% endblock %}
  </div>
</main>
{% include 'misc/footer.html' %}

</body>

</html> 

yatube/templates/misc/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center ">
    <a href="{% url 'about:author' %}">Об авторе</a>
    <a href="{% url 'about:tech' %}">О Технологии</a>
  </p>
  <p class="m-0 text-dark text-center ">
    Социальная сеть <span style="color:red">Ya</span>tube © {{ year }}, все
    права защищены.
  </p>
  <p class="m-0 text-dark text-center "> Зарегистрированных пользователей:
     {{ user_count }}
  </p>
</footer>

yatube/templates/misc/nav.html
<head>
{% load static %}
   <link rel="stylesheet" href="{% static 'posts/style.css' %}">
</head>
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="/"><span style="color:red">Ya</span>tube</a>
      {% comment %}
      Меню - список пунктов со стандартными классами Bootsrap.
      Класс nav-pills нужен для выделения активных пунктов
      {% endcomment %}
  <nav class="nav nav-pills">
    {% if user.is_authenticated %}
     <div class="dropdown">
     <button class="btn btn dropdown-toggle" type="button" id="dropdownMenuButton"
             data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
       <a class="nav-link"></a>{{ user.username }}</button>
       <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
       {% with request.resolver_match.view_name as view_name %}

         <li class="nav-item">
        <a class="nav-link dropdown-item
            {% if view_name == 'edit' %}active{% endif %}"
            href="{% url 'edit' %}">Изменить профиль</a></li>
         <li class="nav-item">
         <a class="nav-link dropdown-item {% if view_name == 'profile' %}active{% endif %}"
                      href="{% url 'profile' user.username %}">Просмотр профиля</a></li>
         <li class="nav-item">

        <a class="nav-link dropdown-item {% if view_name == 'password_change' %}active{% endif %}"
           href="{% url 'password_change' %}">Изменить
        пароль</a></li>
      </div>

      <a class="p-2 text-dark" href="{% url 'post_create' %}">Создать запись</a>

      <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
      {% endwith %}

    {% else %}
      <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
      <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
    {% endif %}

       </div>
  </nav>
</nav>

yatube/templates/misc/paginator.html
<!-- Отрисовываем навигацию паджинатора только если
все посты не помещаются на первую страницу, если есть другие страницы -->
{% if page.has_other_pages %}
  <nav>
    <ul class="pagination">
      {% if page.has_previous %}
        <li class="page-item">
          <a
                  class="page-link"
                  href="?page={{ page.previous_page_number }}">&laquo;
            Назад</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">&laquo; Назад</span>
        </li>
      {% endif %}
      {% for i in page.paginator.page_range %}
        {% if page.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}
              <span class="sr-only">(текущая)</span>
            </span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page.has_next %}
        <li class="page-item">
          <a
                  class="page-link"
                  href="?page={{ page.next_page_number }}">Вперед &raquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Вперед &raquo;</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}